version: "3"

services:
  
  send:
    image: '${DOCKER_SEND_IMAGE}'
    restart: always
    ports:
      - '1234:1234'
    volumes:
      - ./uploads:/uploads
    environment:
      - DHPARAM_GENERATION=false
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - NODE_ENV=production
      - BASE_URL=${SEND_BASE_URL}
      - PORT=1234
      - REDIS_HOST=redis

      # For local uploads storage
      - FILE_DIR=/uploads

      # For S3 object storage (disable volume and FILE_DIR variable)
      # - AWS_ACCESS_KEY_ID=********
      # - AWS_SECRET_ACCESS_KEY=********
      # - S3_BUCKET=send
      # - S3_ENDPOINT=s3.us-west-2.amazonaws.com
      # - S3_USE_PATH_STYLE_ENDPOINT=true

      # To customize upload limits
      # - EXPIRE_TIMES_SECONDS=3600,86400,604800,2592000,31536000
      # - DEFAULT_EXPIRE_SECONDS=3600
      # - MAX_EXPIRE_SECONDS=31536000
      # - DOWNLOAD_COUNTS=1,2,5,10,15,25,50,100,1000
      # - MAX_DOWNLOADS=1000
      # - MAX_FILE_SIZE=2684354560
  
  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - send-redis:/data

volumes:
  send-redis:
